### ISSUE TITLE
User is not authenticated

### ISSUE THREAD

**Issue by IvelinYR** [IvelinYR/Scrum#4]
Given that user is an authorised user
And he has not yet authenticated
When he try to visits the URL for reporting files
Then he is challenged by a login screen
And, upon authentication, he is redirected to the report blank

test scenario:
when user is authorised and try to login
then user  ~~can not login~~ is logged

**Comment by mgenov** [comment]
I'm not sure that you understand correctly the difference between authenticated and authorized.

**Comment by IvelinYR** [comment]
I think that authorised is when  user has active and correct  name and password.
Authenticated is when user is logged.
